services:
  app:
    build: .
    # image: [image-name]
    container_name: python-server
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80      
      - 5678:5678 ## REQUIRED FOR REMOTE DEBUGGING
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:alpine
